import { GitHubProvider } from '../../src/providers/github-provider';

// Mock the octokit module
jest.mock('octokit', () => ({
  Octokit: jest.fn(),
}));

describe('GitHubProvider.createReleasePR', () => {
  it('creates a branch, commits files, creates a PR, adds labels and returns the PR number', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    (provider as any).client = {
      rest: {
        git: {
          getRef: jest.fn().mockResolvedValue({
            data: { object: { sha: 'base-commit-sha' } }
          }),
          createRef: jest.fn().mockResolvedValue({}),
          getCommit: jest.fn().mockResolvedValue({
            data: { tree: { sha: 'tree-sha' } }
          }),
          createBlob: jest.fn().mockResolvedValue({
            data: { sha: 'blob-sha' }
          }),
          createTree: jest.fn().mockResolvedValue({
            data: { sha: 'new-tree-sha' }
          }),
          createCommit: jest.fn().mockResolvedValue({
            data: { sha: 'new-commit-sha' }
          }),
          updateRef: jest.fn().mockResolvedValue({}),
        },
        pulls: {
          create: jest.fn().mockResolvedValue({
            data: { number: 55, html_url: 'https://github.com/owner/repo/pull/55' }
          }),
        },
        issues: {
          addLabels: jest.fn().mockResolvedValue({}),
        },
      },
    } as any;

    const files = [{ path: 'CHANGELOG.md', content: '## v1.2.3\n\nfeatures', status: 'created' } as any];

    const prId = await (provider as any).createReleasePR(
      'chore(main): Release v1.2.3',
      '## v1.2.3\n\nfeatures',
      'release/arp--main',
      'main',
      'main',
      files,
      ['arp: v1.2.3', 'autorelease: pending'],
      '1.2.3'
    );

    expect(prId).toBe(55);

    expect((provider as any).client.rest.pulls.create).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      title: 'chore(main): Release v1.2.3',
      body: '## v1.2.3\n\nfeatures',
      head: 'release/arp--main',
      base: 'main',
    });

    expect((provider as any).client.rest.issues.addLabels).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      issue_number: 55,
      labels: ['arp: v1.2.3', 'autorelease: pending'],
    });
  });
});

describe('GitHubProvider.updateReleasePR', () => {
  it('commits files and updates pull request', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    // Set internal client to mocks
    (provider as any).client = {
      rest: {
        git: {
          getRef: jest.fn().mockResolvedValue({
            data: { object: { sha: 'base-commit-sha' } }
          }),
          getCommit: jest.fn().mockResolvedValue({
            data: { tree: { sha: 'tree-sha' } }
          }),
          createBlob: jest.fn().mockResolvedValue({
            data: { sha: 'blob-sha' }
          }),
          createTree: jest.fn().mockResolvedValue({
            data: { sha: 'new-tree-sha' }
          }),
          createCommit: jest.fn().mockResolvedValue({
            data: { sha: 'new-commit-sha' }
          }),
          updateRef: jest.fn().mockResolvedValue({}),
        },
        pulls: {
          update: jest.fn().mockResolvedValue({
            data: { html_url: 'https://github.com/owner/repo/pull/42' }
          }),
        },
        issues: {
          setLabels: jest.fn().mockResolvedValue({}),
        },
      },
    } as any;

    const files = [{ path: 'CHANGELOG.md', content: 'abc', status: 'created' } as any];

    await (provider as any).updateReleasePR(
      'chore(main): Release v1.2.3',
      'Release 1.2.3\n\nGenerated by another-release-please',
      '42',
      'release/arp--main',
      'main',
      'main',
      files,
      ['arp: v1.2.3'],
      '1.2.3'
    );

    // Verify commit workflow
    expect((provider as any).client.rest.git.getRef).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      ref: 'heads/main',
    });

    expect((provider as any).client.rest.git.createBlob).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      content: expect.any(String),
      encoding: 'base64',
    });

    expect((provider as any).client.rest.git.createTree).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      base_tree: 'tree-sha',
      tree: expect.any(Array),
    });

    expect((provider as any).client.rest.git.createCommit).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      message: expect.any(String),
      tree: 'new-tree-sha',
      parents: ['base-commit-sha'],
    });

    expect((provider as any).client.rest.git.updateRef).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      ref: 'heads/release/arp--main',
      sha: 'new-commit-sha',
      force: true,
    });

    // Verify PR update
    expect((provider as any).client.rest.pulls.update).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      pull_number: 42,
      title: 'chore(main): Release v1.2.3',
      body: expect.any(String),
      state: 'open',
    });

    expect((provider as any).client.rest.issues.setLabels).toHaveBeenCalledWith({
      owner: 'owner',
      repo: 'repo',
      issue_number: 42,
      labels: ['arp: v1.2.3'],
    });
  });
});

describe('GitHubProvider.findPullRequestByBranch (label-only search)', () => {
  it('returns the most recent merged PR for a given label when source/target branches are omitted', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    const mockPR = {
      number: 42,
      title: 'chore(main): Release v1.2.3',
      body: '',
      head: { ref: 'release/arp--main' },
      base: { ref: 'main' },
      state: 'closed',
      draft: false,
      labels: [{ name: 'autorelease: pending' }],
      created_at: '2020-01-01T00:00:00Z',
      updated_at: '2020-01-02T00:00:00Z',
      merged_at: '2020-01-02T00:00:00Z',
      html_url: 'https://github.com/owner/repo/pull/42',
      merge_commit_sha: 'merge-sha',
    };

    const listFn = jest.fn().mockResolvedValue({ data: [mockPR] });
    (provider as any).client = {
      rest: {
        pulls: { list: listFn },
      },
    } as any;

    const pr = await (provider as any).findPullRequestByBranch('dummy', 'dummy', 'autorelease: pending', 'merged');

    expect(listFn).toHaveBeenCalledWith(
      expect.objectContaining({
        owner: 'owner',
        repo: 'repo',
        state: 'closed',
        head: 'owner:dummy',
        base: 'dummy',
      })
    );
    expect(pr.length).toBe(1);
    expect(pr[0].state).toBe('merged');
    expect(pr[0].number).toBe(42);
  });
});

describe('GitHubProvider.findPullRequestByBranch', () => {
  it('respects the state parameter and returns a PR when found', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    const mockPR = {
      number: 43,
      title: 'chore(main): Release v2.0.0',
      body: '',
      head: { ref: 'release/2' },
      base: { ref: 'main' },
      state: 'open',
      draft: false,
      labels: [{ name: 'autorelease: pending' }],
      created_at: '2020-02-01T00:00:00Z',
      updated_at: '2020-02-02T00:00:00Z',
      merged_at: null,
      html_url: 'https://github.com/owner/repo/pull/43',
      merge_commit_sha: null,
    };

    const listFn = jest.fn().mockResolvedValue({ data: [mockPR] });
    (provider as any).client = {
      rest: {
        pulls: { list: listFn },
      },
    } as any;

    const pr = await (provider as any).findPullRequestByBranch('release/2', 'main', 'autorelease: pending', 'open');

    expect(listFn).toHaveBeenCalledWith(
      expect.objectContaining({
        owner: 'owner',
        repo: 'repo',
        state: 'open',
        head: 'owner:release/2',
        base: 'main',
      })
    );
    expect(pr.length).toBe(1);
    expect(pr[0].state).toBe('open');
    expect(pr[0].number).toBe(43);
  });

  it('returns empty array when no PRs match the label', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    const mockPR = {
      number: 44,
      title: 'some other PR',
      body: '',
      head: { ref: 'feature/x' },
      base: { ref: 'main' },
      state: 'open',
      draft: false,
      labels: [{ name: 'some-other-label' }],
      created_at: '2020-03-01T00:00:00Z',
      updated_at: '2020-03-02T00:00:00Z',
      merged_at: null,
      html_url: 'https://github.com/owner/repo/pull/44',
      merge_commit_sha: null,
    };

    const listFn = jest.fn().mockResolvedValue({ data: [mockPR] });
    (provider as any).client = {
      rest: {
        pulls: { list: listFn },
      },
    } as any;

    const result = await (provider as any).findPullRequestByBranch('feature/x', 'main', 'autorelease: pending', 'open');

    expect(result).toEqual([]);
  });

  it('returns empty array when the API returns no PRs', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    const listFn = jest.fn().mockResolvedValue({ data: [] });
    (provider as any).client = {
      rest: {
        pulls: { list: listFn },
      },
    } as any;

    const result = await (provider as any).findPullRequestByBranch('release/arp--main', 'main', 'autorelease: pending', 'open');

    expect(result).toEqual([]);
  });

  it('returns multiple PRs when multiple match', async () => {
    const provider = new GitHubProvider('https://github.com/owner/repo', 'token');

    const makePR = (number: number) => ({
      number,
      title: `chore(main): Release v1.0.${number}`,
      body: '',
      head: { ref: 'release/arp--main' },
      base: { ref: 'main' },
      state: 'open',
      draft: false,
      labels: [{ name: 'autorelease: pending' }],
      created_at: '2020-01-01T00:00:00Z',
      updated_at: '2020-01-02T00:00:00Z',
      merged_at: null,
      html_url: `https://github.com/owner/repo/pull/${number}`,
      merge_commit_sha: null,
    });

    const listFn = jest.fn().mockResolvedValue({ data: [makePR(10), makePR(11)] });
    (provider as any).client = {
      rest: {
        pulls: { list: listFn },
      },
    } as any;

    const result = await (provider as any).findPullRequestByBranch('release/arp--main', 'main', 'autorelease: pending', 'open');

    expect(result.length).toBe(2);
    expect(result[0].number).toBe(10);
    expect(result[1].number).toBe(11);
  });
});
