import { GitLabProvider } from '../../src/providers/gitlab-provider';

describe('GitLabProvider.createReleasePR', () => {
  it('commits files using title as commit message and creates merge request', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');

    (provider as any).projectId = 123;
    (provider as any).projectPath = 'owner/repo';
    (provider as any).client = {
      Commits: { create: jest.fn().mockResolvedValue({}) },
      MergeRequests: { create: jest.fn().mockResolvedValue({ iid: 7, web_url: 'https://gitlab.com/owner/repo/-/merge_requests/7' }) },
    } as any;

    const files = [{ path: 'CHANGELOG.md', content: '## v1.2.3\n\nfeatures', status: 'created' } as any];

    const prId = await (provider as any).createReleasePR('chore(main): Release v1.2.3', '## v1.2.3\n\nfeatures', 'release/arp--main', 'main', 'main', files, ['arp: v1.2.3'], '1.2.3');

    expect(prId).toBe(7);

    expect((provider as any).client.Commits.create).toHaveBeenCalledWith(
      'owner/repo',
      'release/arp--main',
      'chore(main): Release v1.2.3',
      expect.any(Array),
      { startBranch: 'main', force: true }
    );

    expect((provider as any).client.MergeRequests.create).toHaveBeenCalledWith(
      'owner/repo',
      'release/arp--main',
      'main',
      'chore(main): Release v1.2.3',
      expect.objectContaining({ description: expect.any(String), labels: expect.any(Array) })
    );
  });
});

describe('GitLabProvider.updateReleasePR', () => {
  it('commits files and updates merge request', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');

    // Set internal client and project id/path to mocks
    (provider as any).projectId = 123;
    (provider as any).projectPath = 'owner/repo';
    (provider as any).client = {
      Commits: { create: jest.fn().mockResolvedValue({}) },
      MergeRequests: { edit: jest.fn().mockResolvedValue({ web_url: 'https://gitlab.com/owner/repo/-/merge_requests/42' }) },
    } as any;

    const files = [{ path: 'CHANGELOG.md', content: 'abc', status: 'created' } as any];

    await (provider as any).updateReleasePR('chore(main): Release v1.2.3', 'Release 1.2.3\n\nGenerated by another-release-please', '42', 'release/arp--main', 'main', 'main', files, ['arp: v1.2.3'], '1.2.3');

    expect((provider as any).client.Commits.create).toHaveBeenCalledWith(
      'owner/repo',
      'release/arp--main',
      'chore(main): Release v1.2.3',
      expect.any(Array),
      { startBranch: 'main', force: true }
    );

    expect((provider as any).client.MergeRequests.edit).toHaveBeenCalledWith(
      123,
      42,
      expect.objectContaining({ title: 'chore(main): Release v1.2.3', description: expect.any(String), labels: expect.any(Array) })
    );
  });
});


describe('GitLabProvider.findPullRequestByBranch (label-only search)', () => {
  it('returns the most recent merged MR for a given label when source/target branches are omitted', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');
    (provider as any).projectId = 123;
    const mockMR = [{
      iid: 42,
      title: 'chore(main): Release v1.2.3',
      description: '',
      source_branch: 'release/arp--main',
      target_branch: 'main',
      state: 'merged',
      labels: ['autorelease: pending'],
      created_at: '2020-01-01T00:00:00Z',
      updated_at: '2020-01-02T00:00:00Z',
      merged_at: '2020-01-02T00:00:00Z',
      web_url: 'https://gitlab.com/owner/repo/-/merge_requests/42'
    }];

    const allFn = jest.fn().mockResolvedValue(mockMR);
    (provider as any).client = { MergeRequests: { all: allFn } } as any;

    const pr = await (provider as any).findPullRequestByBranch('dummy', 'dummy', 'autorelease: pending', 'merged');

    expect(allFn).toHaveBeenCalledWith(expect.objectContaining({ labels: 'autorelease: pending', state: 'merged' }));
    expect(pr.length).toBe(1);
    expect(pr[0].state).toBe('merged');
    expect(pr[0].number).toBe(42);
  });
});


describe('GitLabProvider.findPullRequestByBranch', () => {
  it('respects the state parameter and returns a PR when found', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');
    (provider as any).projectId = 123;
    const mockMR = [{
      iid: 43,
      title: 'chore(main): Release v2.0.0',
      description: '',
      source_branch: 'release/2',
      target_branch: 'main',
      state: 'opened',
      labels: ['autorelease: pending'],
      created_at: '2020-02-01T00:00:00Z',
      updated_at: '2020-02-02T00:00:00Z',
      web_url: 'https://gitlab.com/owner/repo/-/merge_requests/43'
    }];

    const allFn = jest.fn().mockResolvedValue(mockMR);
    (provider as any).client = { MergeRequests: { all: allFn } } as any;

    const pr = await (provider as any).findPullRequestByBranch('release/2', 'main', 'autorelease: pending', 'open');

    expect(allFn).toHaveBeenCalledWith(expect.objectContaining({ sourceBranch: 'release/2', targetBranch: 'main', labels: 'autorelease: pending', state: 'opened' }));
    expect(pr.length).toBe(1);
    expect(pr[0].state).toBe('open');
    expect(pr[0].number).toBe(43);
  });

  it('uses perPage: 5 when fetching MRs', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');
    (provider as any).projectId = 123;
    (provider as any).projectPath = 'owner/repo';

    const allFn = jest.fn().mockResolvedValue([]);
    (provider as any).client = { MergeRequests: { all: allFn } } as any;

    await (provider as any).findPullRequestByBranch('release/arp--main', 'main', 'autorelease: pending', 'open');

    expect(allFn).toHaveBeenCalledWith(expect.objectContaining({ perPage: 5 }));
  });

  it('returns empty array when no MRs are found', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');
    (provider as any).projectId = 123;
    (provider as any).projectPath = 'owner/repo';

    const allFn = jest.fn().mockResolvedValue([]);
    (provider as any).client = { MergeRequests: { all: allFn } } as any;

    const result = await (provider as any).findPullRequestByBranch('release/arp--main', 'main', 'autorelease: pending', 'open');

    expect(result).toEqual([]);
  });

  it('returns multiple MRs when multiple match', async () => {
    const provider = new GitLabProvider('https://gitlab.com/owner/repo', 'token');
    (provider as any).projectId = 123;
    (provider as any).projectPath = 'owner/repo';

    const makeMR = (iid: number) => ({
      iid,
      title: `chore(main): Release v1.0.${iid}`,
      description: '',
      source_branch: 'release/arp--main',
      target_branch: 'main',
      state: 'opened',
      labels: ['autorelease: pending'],
      created_at: '2020-01-01T00:00:00Z',
      updated_at: '2020-01-02T00:00:00Z',
      web_url: `https://gitlab.com/owner/repo/-/merge_requests/${iid}`,
    });

    const allFn = jest.fn().mockResolvedValue([makeMR(10), makeMR(11)]);
    (provider as any).client = { MergeRequests: { all: allFn } } as any;

    const result = await (provider as any).findPullRequestByBranch('release/arp--main', 'main', 'autorelease: pending', 'open');

    expect(result.length).toBe(2);
    expect(result[0].number).toBe(10);
    expect(result[1].number).toBe(11);
  });
});
